version: "3"

services:

  db:
    container_name: lcwc_db
    image: mysql:5.7
    ports:
      - 32001:3306
    environment:
      - MYSQL_USER=lcwc
      - MYSQL_PASSWORD=lcwc
      - MYSQL_DATABASE=lcwc_api
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - lcwc-network

  app:
    build: .
    container_name: lcwc_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - lcwc-network
    

networks:
  lcwc-network:
    driver: bridge